---
sudo: required
language: python
services:
  - docker

install:
  - pip3 install ansible ansible-lint
  # Install test dependencies.
  - pip3 install molecule molecule-docker

script:
  # Run tests.
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
