---
- name: Update and upgrade apt packages
  apt:
    update_cache: true
    cache_valid_time: 86400

- name: Install asterisk prerequisites
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - gcc
      - cpp
      - make
      - unixodbc
      - unixodbc-dev
      - python-dev-is-python3
      - python3-pip
      - python3-pymysql
      - lame
      - odbcinst
      - wget
      - unzip
      - ufw

- name: Remove existing install source dir
  file: "path={{ asterisk_src_dir }} state=absent"

- name: Create install source dir
  file:
    path: "{{ asterisk_src_dir }}"
    state: directory
    mode: "0760"

- name: Download Asterisk source.
  get_url:
    url: http://downloads.asterisk.org/pub/telephony/asterisk/asterisk-{{ asterisk_version }}-current.tar.gz
    dest: /tmp
  when: not asterisk_status.stat.exists
  tags: skip_ansible_lint

- name: Extract Asterisk source.
  unarchive:
    src: "/tmp/asterisk-{{ asterisk_version }}-current.tar.gz"
    dest: "{{ asterisk_src_dir }}"
    remote_src: "yes"
    extra_opts: ['--strip-components=1']

- name: Let asterisk install dependencies
  shell: 'export DEBIAN_FRONTEND=noninteractive && yes |
  ./contrib/scripts/install_prereq install chdir={{ asterisk_src_dir }}'
  when: not asterisk_status.stat.exists
  tags: skip_ansible_lint

- name: Configure asterisk
  command: ./configure --with-jansson-bundled chdir={{ asterisk_src_dir }}
  when: not asterisk_status.stat.exists

- name: Create menuselect.makeopts
  command: make menuselect chdir={{ asterisk_src_dir }}
  when: not asterisk_status.stat.exists

- name: Do a bit of menuselect configuration
  command: "{{ item }} chdir={{ asterisk_src_dir }}"
  with_items:
    - 'menuselect/menuselect --enable format_mp3'
    - 'menuselect/menuselect --enable codec_opus'
    - 'menuselect/menuselect --enable codec_siren7'
    - 'menuselect/menuselect --enable codec_siren14'
    - 'menuselect/menuselect --disable CORE-SOUNDS-EN-GSM'
    - 'menuselect/menuselect --disable cdr_radius'
    - 'menuselect/menuselect --enable CORE-SOUNDS-EN-WAV'
    - 'menuselect/menuselect --enable CORE-SOUNDS-EN-G722'
    - 'menuselect/menuselect  --enable EXTRA-SOUNDS-EN-GSM'
    - 'menuselect/menuselect --enable EXTRA-SOUNDS-EN-WAV'
    - 'menuselect/menuselect --enable EXTRA-SOUNDS-EN-G722'

  when: not asterisk_status.stat.exists

- name: Make
  command: make  chdir={{ asterisk_src_dir }}
  when: not asterisk_status.stat.exists

- name: Install
  command: make install chdir={{ asterisk_src_dir }}
  when: not asterisk_status.stat.exists

- name: Make samples
  command: make samples chdir={{ asterisk_src_dir }}
  when: not asterisk_status.stat.exists

- name: Install the initscript
  command: make config chdir={{ asterisk_src_dir }}
  when: not asterisk_status.stat.exists

- name: Make sure the default asterisk service is enabled
  service:
    name: "asterisk"
    enabled: yes

- name: Add Asterisk user
  user:
    name: "{{ asterisk_user }}"
    state: present
    comment: "Asterisk User"


  # Ignore ufw errors while testing
- name: tweak the ufw firewall for UDP/SIP
  ignore_errors: yes
  ufw:
    rule: allow
    port: 5060
    proto: udp


- name: tweak the ufw firewall for UDP/RTP
  ignore_errors: yes
  ufw:
    rule: allow
    port: 10000:20000
    proto: udp
