---
- name: install ntpd
  apt:
    name:
      - ntp
      - ntpdate

- name: stop time service
  service:
    name: systemd-timesyncd
    state: stopped
    enabled: no

- name: Ensure NTP is running
  service:
    name: ntp
    state: started
    enabled: yes
