---
- name: Install unzip and xz-utils
  apt:
    name:
      - unzip
      - xz-utils

- name: Install mysql community client plugins
  apt:
    deb: "{{ mysql_community_plugins_deb_package_url }}"
    update_cache: yes

- name: Install ODBC
  apt:
    deb: "{{ odbc_deb_package_url }}"
    update_cache: yes

- name: Make sure asterisk_odbc_driver_path is owned by root
  file:
    path: /usr/lib/x86_64-linux-gnu/odbc/
    owner: root
    recurse: yes
    group: root
    mode: 0775
