---
- name: Check For Updates
  include_tasks: install_updates.yml

- name: Variables
  include_tasks: variables.yml

- name: NTP
  include_tasks: install_ntp.yml

- name: Mysql
  include_tasks: mysql.yml

- name: Asterisk Installation
  include_tasks: install.yml
  when: not asterisk_status.stat.exists

- include_tasks: install_odbc.yml
  when: not odbc_driver.stat.exists

- include_tasks: install_alembic.yml
  when: not alembic_config.stat.exists

- name: push configs
  include_tasks: push_configs.yml
