---
- name: Install MySQL
  apt:
    name:
      - mysql-server
      - python3-pymysql

- name: Start the MySQL service
  service:
    name: mysql
    state: started
    enabled: true

- name: Copy the root credentials as .my.cnf file
  template: src=root.cnf.j2 dest=/root/.my.cnf mode=0600

- name: Copy the mysqld.cnf
  template: src=mysqld.cnf.j2 dest=/etc/mysql/mysql.conf.d/mysqld.cnf mode=0600


- name: Update MySQL root password for all root accounts
  mysql_user: 'name=root host={{ item }} password={{ mysql_root_password }}
  state=present login_unix_socket="{{ mysql_socket }}"'
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: Ensure Anonymous user(s) are not in the database
  mysql_user: "name='' host={{ item }} state=absent
  login_unix_socket={{ mysql_socket }}
  login_user=root login_password={{ mysql_root_password }}"
  with_items:
    - localhost
    - "{{ ansible_hostname }}"

- name: Create a new database
  mysql_db:
    name: "{{ mysql_asterisk_database }}"
    state: present
    login_unix_socket: "{{ mysql_socket }}"

- name: Create a mysql user
  mysql_user:
    name: "{{ mysql_asterisk_user }}"
    password: "{{ mysql_asterisk_user_password }}"
    host: "{{ mysql_host }}"
    priv: "{{ mysql_asterisk_user_priv }}"
    state: present
    login_unix_socket: "{{ mysql_socket }}"

